CREATE SCHEMA IF NOT EXISTS ev_charging_bronze;

CREATE TABLE IF NOT EXISTS ev_charging_bronze.raw_charging_events (
    user_id STRING,
    vehicle_model STRING,
    battery_capacity_kwh DOUBLE,
    charging_station_id STRING,
    charging_station_location STRING,
    charging_start_time TIMESTAMP,
    charging_end_time TIMESTAMP,
    energy_consumed_kwh DOUBLE,
    charging_duration_hours DOUBLE,
    charging_rate_kw DOUBLE,
    charging_cost_usd DOUBLE,
    time_of_day STRING,
    day_of_week STRING,
    soc_start_percent DOUBLE,
    soc_end_percent DOUBLE,
    distance_since_last_charge_km DOUBLE,
    source_temperature_c DOUBLE,
    vehicle_age_years DOUBLE,
    charger_type STRING,
    user_type STRING,
    station_name STRING,
    latitude DOUBLE,
    longitude DOUBLE,
    rating DOUBLE,
    review_count DOUBLE,
    address STRING,
    city STRING,
    state STRING,
    zip STRING,
    phone STRING,
    hours STRING,
    num_connectors DOUBLE,
    total_kw DOUBLE,
    website STRING,
    station_source_identifier STRING,
    station_match_status STRING,
    temperature_c DOUBLE,
    humidity_percent DOUBLE,
    precipitation_mm DOUBLE,
    wind_speed_kph DOUBLE,
    weather_condition STRING,
    traffic_score DOUBLE,
    traffic_level STRING,
    road_congestion_index DOUBLE,
    nearby_events_count DOUBLE
)
USING DELTA;

